config/routes.rb
Rails.application.routes.draw do

  resources :administradors
  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'

  resources :estoques do
    resources :items
  end
  resources :fornecedors do
    resources :contratos
  end

  root 'sessions#new'

end

app/models/estoque.rb
class Estoque < ApplicationRecord
  validates :nome, presence: true, length: {minimum: 6}
  has_many :items, dependent: :destroy
end

app/controllers/estoques_controller.rb
class EstoquesController < ApplicationController
  before_action :set_estoque, only: [:show, :edit, :update, :destroy]

  # GET /estoques
  # GET /estoques.json
  def index
    @estoques = Estoque.all
  end

  # GET /estoques/1
  # GET /estoques/1.json
  def show
    @estoque = Estoque.find(params[:id])
  end

  # GET /estoques/new
  def new
    @estoque = Estoque.new
  end

  # GET /estoques/1/edit
  def edit
  end

  # POST /estoques
  # POST /estoques.json
  def create
    @estoque = Estoque.new(estoque_params)

    respond_to do |format|
      if @estoque.save
        format.html { redirect_to @estoque, notice: 'Estoque was successfully created.' }
        format.json { render :show, status: :created, location: @estoque }
      else
        format.html { render :new }
        format.json { render json: @estoque.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estoques/1
  # PATCH/PUT /estoques/1.json
  def update
    respond_to do |format|
      if @estoque.update(estoque_params)
        format.html { redirect_to @estoque, notice: 'Estoque was successfully updated.' }
        format.json { render :show, status: :ok, location: @estoque }
      else
        format.html { render :edit }
        format.json { render json: @estoque.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estoques/1
  # DELETE /estoques/1.json
  def destroy
    @estoque.destroy
    respond_to do |format|
      format.html { redirect_to estoques_url, notice: 'Estoque was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estoque
      @estoque = Estoque.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estoque_params
      params.require(:estoque).permit(:nome)
    end
end

app/helpers/estoques_helper.rb
module EstoquesHelper
end

app/views/estoques/_form.html.erb
<%= form_with(model: estoque, local: true) do |form| %>
  <% if estoque.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estoque.errors.count, "error") %> prohibited this estoque from being saved:</h2>

      <ul>
      <% estoque.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :estoque_nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estoques/_form2.html.erb
<p>
  <h1>
  <%= @estoque.nome %>
  </h1>
</p>

<h3>Itens:</h3>
<% @estoque.items.each do |item| %>
  <table>
    <tr>
      <th><strong>Nome:</strong></th>
      <th><%= item.nome %></th>
    </tr>

    <tr>
      <th><strong>Data de validade:</strong></th>
      <th><%= item.data_val %></th>
    </tr>

    <tr>
      <th><strong>Numero do lote:</strong></th>
      <th><%= item.n_lote %></th>
    </tr>

    <tr>
      <th><strong>Descricao:</strong></th>
      <th><%= item.desc %></th>
    </tr>

    <tr>
      <th><strong>Unidade:</strong></th>
      <th><%= item.unidade %></th>
    </tr>
  </table>

<%= link_to 'Excluir Item' %>
<%end%>

<h3>Adicionar Item:</h3>
<%= form_with(model: [ @estoque, @estoque.items.build ], local: true) do |form| %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :data_val %>
    <%= form.text_field :data_val %>
  </div>

  <div class="field">
    <%= form.label :n_lote %>
    <%= form.text_field :n_lote %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="field">
    <%= form.label :unidade %>
    <%= form.number_field :unidade %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estoques/edit.html.erb
<h1>Editing Estoque</h1>

<%= render 'form', estoque: @estoque %>

<%= link_to 'Show', @estoque %> |
<%= link_to 'Back', estoques_path %>

app/views/estoques/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estoques</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estoques.each do |estoque| %>
      <tr>
        <td><%= estoque.nome %></td>
        <td><%= link_to 'Ver', estoque, id:"s-#{estoque.nome}" %></td>
        <td><%= link_to 'Editar', edit_estoque_path(estoque), id:"e-#{estoque.nome}" %></td>
        <td><%= link_to 'Excluir', estoque, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Estoque', new_estoque_path %> <%= link_to 'Voltar', root_path %>

app/views/estoques/new.html.erb
<h1>New Estoque</h1>

<%= render 'form', estoque: @estoque %>

<%= link_to 'Back', estoques_path %>

app/views/estoques/show.html.erb
<p id="notice"><%= notice %></p>

<%= render "form2", estoque: @estoque %>

<%= link_to 'Edit', edit_estoque_path(@estoque) %> |
<%= link_to 'Back', estoques_path %>