config/routes.rb
Rails.application.routes.draw do

  resources :administradors
  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'

  resources :estoques do
    resources :items
  end
  resources :fornecedors do
    resources :contratos
  end

  root 'sessions#new'

end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
  validates :nome, presence: true, length: {minimum: 6}
  validates :cnpj, presence: true, length: {minimum: 14}
  has_many :contratos, dependent: :destroy
end

app/controllers/fornecedors_controller.rb
class FornecedorsController < ApplicationController
  before_action :set_fornecedor, only: [:show, :edit, :update, :destroy]

  # GET /fornecedors
  # GET /fornecedors.json
  def index
    @fornecedors = Fornecedor.all
  end

  # GET /fornecedors/1
  # GET /fornecedors/1.json
  def show
    @fornecedor = Fornecedor.find(params[:id])
  end

  # GET /fornecedors/new
  def new
    @fornecedor = Fornecedor.new
  end

  # GET /fornecedors/1/edit
  def edit
  end

  # POST /fornecedors
  # POST /fornecedors.json
  def create
    @fornecedor = Fornecedor.new(fornecedor_params)

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to @fornecedor, notice: 'Fornecedor was successfully created.' }
        format.json { render :show, status: :created, location: @fornecedor }
      else
        format.html { render :new }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fornecedors/1
  # PATCH/PUT /fornecedors/1.json
  def update
    respond_to do |format|
      if @fornecedor.update(fornecedor_params)
        format.html { redirect_to @fornecedor, notice: 'Fornecedor was successfully updated.' }
        format.json { render :show, status: :ok, location: @fornecedor }
      else
        format.html { render :edit }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedors/1
  # DELETE /fornecedors/1.json
  def destroy
    @fornecedor.destroy
    respond_to do |format|
      format.html { redirect_to fornecedors_url, notice: 'Fornecedor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fornecedor
      @fornecedor = Fornecedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fornecedor_params
      params.require(:fornecedor).permit(:nome, :cnpj)
    end
end

app/helpers/fornecedors_helper.rb
module FornecedorsHelper
end

app/views/fornecedors/_form.html.erb
<%= form_with(model: fornecedor, local: true) do |form| %>
  <% if fornecedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fornecedor.errors.count, "error") %> prohibited this fornecedor from being saved:</h2>

      <ul>
      <% fornecedor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :fornecedor_nome %>
  </div>

  <div class="field">
    <%= form.label :cnpj %>
    <%= form.text_field :cnpj, id: :fornecedor_cnpj %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fornecedors/_form2.html.erb
<p>
  <h1>
  <%= @fornecedor.nome %>
  </h1>
</p>

<p>
  <h1>
  <strong>Cnpj:</strong>
  <%= @fornecedor.cnpj %>
  </h1>
</p>

<h3>Contratos:</h3>
<% @fornecedor.contratos.each do |contrato| %>
  <table>
    <tr>
      <th><strong>Numero do contrato:</strong></th>
      <th><%= contrato.n_contrato %></th>
    </tr>

    <tr>
      <th><strong>Data:</strong></th>
      <th><%= contrato.data %></th>
    </tr>

    <tr>
      <th><strong>Numero do processo:</strong></th>
      <th><%= contrato.n_lic %></th>
    </tr>

    <tr>
      <th><strong>Descricao:</strong></th>
      <th><%= contrato.desc %></th>
    </tr>

<%= link_to 'Excluir Contrato' %>
<%end%>

<h3>Novo contrato:</h3>
<%= form_with(model: [ @fornecedor, @fornecedor.contratos.build ], local: true) do |form| %>

  <div class="field">
    <%= form.label :n_contrato %>
    <%= form.text_field :n_contrato %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data %>
  </div>

  <div class="field">
    <%= form.label :n_proc_lic %>
    <%= form.text_field :n_lic %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fornecedors/edit.html.erb
<h1>Editing Fornecedor</h1>

<%= render 'form', fornecedor: @fornecedor %>

<%= link_to 'Show', @fornecedor %> |
<%= link_to 'Back', fornecedors_path %>

app/views/fornecedors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fornecedores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cnpj</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fornecedors.each do |fornecedor| %>
      <tr>
        <td><%= fornecedor.nome %></td>
        <td><%= fornecedor.cnpj %></td>
        <td><%= link_to 'Ver', fornecedor %></td>
        <td><%= link_to 'Editar', edit_fornecedor_path(fornecedor) %></td>
        <td><%= link_to 'Excluir', fornecedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Fornecedor', new_fornecedor_path %> <%= link_to 'Voltar', root_path %>

app/views/fornecedors/new.html.erb
<h1>New Fornecedor</h1>

<%= render 'form', fornecedor: @fornecedor %>

<%= link_to 'Back', fornecedors_path %>

app/views/fornecedors/show.html.erb
<p id="notice"><%= notice %></p>

<%= render "form2" %>

<%= link_to 'Editar', edit_fornecedor_path(@fornecedor) %> |
<%= link_to 'Voltar', fornecedors_path %>